### ISSUE TITLE
Dialog pops up when function defined

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaGizmos/GtkReactive.jl#113]
I have a button and I want it to trigger the NativeFileDialog picker:

```julia
win = Window("Test")
inputfiles = Signal([""])
inputfilebtn = button("Input files")
inputfilebtn_handler = map(inputfilebtn) do btn
    push!(inputfiles, pick_multi_file())
end
push!(win, inputfilebtn)
showall(win)
```

So, this does work to trigger the dialog when the button is pressed. But it also runs when it is first defined, and no button is pressed. Is there a better way to handle this than having a global `is_initializing` variable that all button signal handlers check?

**Comment by BioTurboNick** [comment]
IMO it would be nice if the Signal had a concept of "unset" under which it would not update downstream handlers.

**Comment by timholy** [comment]
That will be easier with https://github.com/JuliaGizmos/GtkObservables.jl since Observables already supports this. https://github.com/JuliaGizmos/Observables.jl/blob/0f94e69cabddd87fcf057fb95ed5dc64be9661de/src/Observables.jl#L247

Reactive is pretty much unmaintained, AFAICT. ProfileView and ImageView intend to migrate but there are segfaults from the tests that need tracking down first.

**Comment by BioTurboNick** [comment]
Oh okay, thanks Tim!
